services:
  sqlite:
    build:
      context: ./SQLite
      dockerfile: Dockerfile
    volumes:
      - sqlite-data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "9000:9000"
    volumes:
      - sqlite-data:/data
      - avatar-uploads:/app/uploads/avatars
      - ./backend:/app:rw
      - /app/node_modules
    environment:
      - SQLITE_DB_PATH=/data/database.sqlite
      - USER=${USER}
    env_file:
      - .env
    depends_on:
      - sqlite

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - ./Game:/app/Game
      - /app/node_modules
    # environment:
    #   - VITE_API_URL=http://192.168.1.123:8888
    #   - VITE_WS_URL=ws://192.168.1.123:8888
    env_file:
      - .env
    depends_on:
      - backend

volumes:
  sqlite-data:
    driver: local
  avatar-uploads:
    driver: local
